// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    AZURE_TENANT_ID: z.string().min(1),
    AZURE_CLIENT_ID: z.string().min(1),
    AZURE_CLIENT_SECRET: z.string().min(1),
    AZURE_BILLING_ACCOUNT_ID: z.string().min(1),
    SMTP_PASSWORD: z.string().min(1),
    SMTP_USERNAME: z.string().min(1),
    SMTP_PORT: z.number({ coerce: true }).min(1),
    SMTP_HOST: z.string().min(1),
    SMTP_FROM: z.string().default("nico@hyperjump.tech").optional(),
    BASE_URL: z.string().min(1),
    JWT_SECRET: z.string().min(1),
    ALLOWED_EMAIL_ADDRESSES: z.string().min(1),
    API_HEALTH_KEY: z.string().min(1),
    NODE_ENV: z.string().default("production").optional(),
  },
  client: {
    NEXT_PUBLIC_COMPANY_NAME: z.string().min(1),
    NEXT_PUBLIC_APP_NAME: z.string().min(1),
    NEXT_PUBLIC_NO_EMAIL_SEND: z.string().optional(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_COMPANY_NAME: process.env.NEXT_PUBLIC_COMPANY_NAME,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_NO_EMAIL_SEND: process.env.NEXT_PUBLIC_NO_EMAIL_SEND,
  }
});
